### ISSUE TITLE
Additional Employee Interface

### ISSUE THREAD

**Issue by Arifah0100** [Arifah0100/information-system-serverside#7]
Create new entity for employee 'Manager', a one-to-one relation to Manager Entity.

Manager - the one who manage the collectors or employee.
Attribute:
manageID: number;
firstName: string;
middleName: string;
lastName: string;
startDate: string;
department: string;
position: string;

**Comment by imsab23** [comment]
manageID ba or empID?

**Comment by Arifah0100** [comment]
manageID
